//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Diciplines = new HashSet<Dicipline>();
        }
    
        public int deptID { get; set; }
        public string name { get; set; }
        public string location { get; set; }
    
        public virtual ICollection<Dicipline> Diciplines { get; set; }
    }
}
