//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dicipline
    {
        public Dicipline()
        {
            this.Sessions = new HashSet<Session>();
        }
    
        public int dicipID { get; set; }
        public string name { get; set; }
        public int deptID { get; set; }
        public int totalSemester { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<Session> Sessions { get; set; }
    }
}
