//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guardian
    {
        public Guardian()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int guardianID { get; set; }
        public string guardianName { get; set; }
        public string relationship { get; set; }
        public string mobileNumber { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
    }
}
