//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public Section()
        {
            this.Classes = new HashSet<Class>();
        }
    
        public int sectionID { get; set; }
        public int sessionID { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Class> Classes { get; set; }
    }
}
