//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public Session()
        {
            this.Classes = new HashSet<Class>();
            this.Students = new HashSet<Student>();
        }
    
        public int sessionID { get; set; }
        public string name { get; set; }
        public int dicipID { get; set; }
        public int year { get; set; }
    
        public virtual ICollection<Class> Classes { get; set; }
        public virtual Dicipline Dicipline { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
