//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Attendances = new HashSet<Attendance>();
            this.Classes = new HashSet<Class>();
        }
    
        public string rollNo { get; set; }
        public int sessionID { get; set; }
        public string fatherName { get; set; }
        public string fullName { get; set; }
        public Nullable<int> guardianID { get; set; }
        public string gender { get; set; }
        public string username { get; set; }
    
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual Guardian Guardian { get; set; }
        public virtual Session Session { get; set; }
        public virtual Userinfo Userinfo { get; set; }
        public virtual ICollection<Class> Classes { get; set; }
    }
}
